[package]
name = "tiny-earley"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[benches]
path = "bench_parser.rs"

[dependencies]

[profile.bench]
opt-level = 3               # Use slightly better optimizations.

[features]
default = ["debug", "rel_compact_forest"]
debug = []
simple = []
extra_inline = []
vec2d = []
simplest_forest = []
simple_forest = []
compact_forest = []
linked_forest = []
forest_size = []
rel_compact_forest =  []
